//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Buddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Files = new HashSet<File>();
            this.Managers = new HashSet<Manager>();
            this.Members = new HashSet<Member>();
            this.Progresses = new HashSet<Progress>();
            this.Requests = new HashSet<Request>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int group_id { get; set; }
        public string visibility { get; set; }
        public string group_name { get; set; }
        public string date_created { get; set; }
        public int uId { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Manager> Managers { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Progress> Progresses { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
