//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Buddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string status { get; set; }
        public string @lock { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string title { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual User User { get; set; }
    }
}
